INSERT INTO `reports`(`reportid`, `content`, `type`, `userid`) 
VALUES 
('1', 'Product A is not available in stock.', 'Stock Issue', NULL),
('2', 'Payment gateway is not responding.', 'Payment Issue', NULL),
('3', 'Order #1234 was delivered late.', 'Delivery Issue', NULL),
('4', 'Bug in the checkout process.', 'Bug Report', NULL),
('5', 'Feedback on the new product line.', 'Feedback', NULL),
('6', 'Received wrong product in order #5678.', 'Order Issue', NULL),
('7', 'Unable to apply discount code DISC001.', 'Discount Issue', NULL),
('8', 'Request to update account information.', 'Account Request', NULL),
('9', 'Product description mismatch for item #7890.', 'Product Issue', NULL),
('10', 'Complaint about customer service.', 'Complaint', NULL),
('11', 'Suggestion to add more payment methods.', 'Suggestion', NULL),
('12', 'Report of fraudulent activity.', 'Security Issue', NULL),
('13', 'System crash during peak hours.', 'Performance Issue', NULL),
('14', 'Difficulty in tracking order status.', 'Order Issue', NULL),
('15', 'Refund for order #8910 not processed.', 'Refund Issue', NULL),
('16', 'Request for invoice of order #6789.', 'Invoice Request', NULL),
('17', 'Website layout issue on mobile devices.', 'Bug Report', NULL),
('18', 'Delivery person was unprofessional.', 'Complaint', NULL),
('19', 'Question about loyalty points.', 'Customer Inquiry', NULL),
('20', 'Technical error during login.', 'Login Issue', NULL)
